# Auto-generated by tools/build_submission.py.
# Source of truth: src/models/* and src/inference/*.
from __future__ import annotations

import re
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import torch
from PIL import Image
from torch import nn
from torch.utils.data import DataLoader, Dataset
from torchvision.models import ResNet18_Weights, resnet18
from torchvision.models.video import mvit_v2_s

S1_MEAN = torch.tensor([0.45, 0.45, 0.45])[:, None, None, None]
S1_STD = torch.tensor([0.225, 0.225, 0.225])[:, None, None, None]
S3_MEAN = torch.tensor([0.45, 0.45, 0.45])[:, None, None]
S3_STD = torch.tensor([0.225, 0.225, 0.225])[:, None, None]
cv2.setNumThreads(1)


# ---- src/models/stage1.py ----
# 1. Configuration

# 1.1. 관련 패키지 임포트
from torch import nn
from torchvision.models.video import mvit_v2_s


class Stage1MViT(nn.Module):
    """
    영상 전체를 하나의 2-class 문제로 분류하는 모델 클래스
    Stage 1의 ORIGINAL / RERECORDED 이진 분류 모델
    """

    def __init__(self):
        # nn.Module의 초기화를 수행
        super().__init__()
        # Torchvision의 MViTv2-Small 모델을 생성
        self.net = mvit_v2_s(weights=None)
        # 기본 MViT의 classification head 변경 (우리는 이진 분류를 원하니 out_features를 2로 조정한다)
        self.net.head[1] = nn.Linear(self.net.head[1].in_features, 2)

    # 입력 x를 MViT에 그대로 넣으면 두 클래스에 대한 logit이 나온다. 이후에 추론에서 softmax를 통해 probability롷 전환한다.
    def forward(self, x): return self.net(x)


# ---- src/models/stage2.py ----
# 1. Configuration

# 1.1. 관련 패키지 임포트
import torch
from torch import nn



class Stage2Temporal(nn.Module):
    """
    입력은 이미 다른 모델에서 추출한 frame-wise feature sequence가 된다.
    입력 feature dimension은 512이다.
    Stage 2: 사고 주요시점·상황 분석 모델
    """

    def __init__(self):
        # nn.Module의 초기화를 수행
        super().__init__()

        # 각 frame feature가 512차원 input_size = 512
        # GRU의 hidden representation 크기는 192 hidden_size = 192
        # GRU layer를 두 층 num_layers = 2
        # 입력 shape이 [B, T, feature] 가 되도록 한다. batch_first=True
        # 양방향 GRU로 설정. 이를 통해 representation의 수가 192x2=384가 된다. bidirectional=True
        # GRU layer 사이에 dropout을 적용 dropout=0.15
        self.r = nn.GRU(512, 192, 2, batch_first=True, bidirectional=True, dropout=0.15)

        # collision head 확인. 각 timestep의 384차원 feature를 scalar 하나로 줄인다.
        # 즉 각 frame마다 "이 frame이 collision frame일 가능성이 얼마나 높은가?"에 대응되는 logit 하나를 생성
        self.tc = nn.Linear(384, 1)
        # entry head 확인. 각 frame마다 하나의 score를 만들지만 이번에는 entry frame을 찾기 위한 것
        self.te = nn.Linear(384, 1)
        # scene classifier. 각 클래스별로 입력으로 받는 feature에 대하여 scene logit을 계산한다.
        self.scene = nn.Sequential(nn.Linear(768, 192), nn.ReLU(), nn.Dropout(0.2), nn.Linear(192, 4))

    def logits(self, x):
        # 입력에 대해 GRU를 통과시킨다.
        # 입력: x = [B,T,512]
        # 출력: h = [B,T,384]
        h, _ = self.r(x)
        # collision score : tc를 통해 확인 [B, T]
        # entry score : te를 통해 확인 [B, T]
        return self.tc(h).squeeze(-1), self.te(h).squeeze(-1), h

    def forward(self, x):
        # logit을 계산한다.
        collision, entry, h = self.logits(x)
        # collision frame과 entry frame 선택
        ci, ei = collision.argmax(1), entry.argmax(1)
        # 각 batch sample에서 선택한 frame의 hidden state를 가져온다.
        b = torch.arange(len(h), device=h.device)
        # 두 feature를 concatenate 한 뒤 self.scene()에 넣는다.
        # predicted collision index
        # predicted entry index
        # scene classification logits
        # 위의 세가지를 최종적으로 제출한다.
        return ci, ei, self.scene(torch.cat([h[b, ci], h[b, ei]], 1))


# ---- src/models/stage3.py ----
# 1. Configuration

# 1.1. 관련 패키지 임포트
from torch import nn
from torchvision.models.video import mvit_v2_s


class Stage3MViT(nn.Module):
    """
    Stage 3: 차량 거동 특성 분석 모델
    """

    def __init__(self):
        # nn.Module의 초기화를 수행
        super().__init__()

        # Torchvision의 MViTv2-Small 모델을 생성
        self.backbone = mvit_v2_s(weights=None)

        # MViT가 최종적으로 생성하는 representation의 dimension 확인
        dim = self.backbone.head[1].in_features

        # classification head 제거
        # 이제 class logits이 아니라 video feature vector가 나온다.
        self.backbone.head = nn.Identity()
        # acceleration 범주 4가지의 classifier 설정
        # ACCELERATING, DECELERATING, CONSTANT, STOPPED
        self.accel = nn.Linear(dim, 4)
        # 조향 범주 3가지 classifier 설정
        # LEFT, STRAIGHT, RIGHT
        self.steer = nn.Linear(dim, 3)

    def forward(self, x):
        # 영상 하나를 하나의 feature vector로 압축
        z = self.backbone(x)
        # 동일한 z를 두 classifier가 공유
        # accel_logits, steer_logits가 나온다.
        return self.accel(z), self.steer(z)


# ---- src/inference/stage1.py ----
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader, Dataset



VIDEO_EXT = {".mp4", ".avi", ".mov", ".mkv", ".m4v", ".3gp", ".3gpp", ".wmv"}


def _device() -> torch.device:
    if not torch.cuda.is_available():
        raise RuntimeError("DACON inference requires a CUDA GPU.")
    return torch.device("cuda")


def _video_paths(root: Path):
    return sorted(p for p in root.rglob("*") if p.is_file() and p.suffix.lower() in VIDEO_EXT)


def _clip_ids(path: Path, n: int, slot: int, slots: int):
    cap = cv2.VideoCapture(str(path))
    total = max(1, int(cap.get(cv2.CAP_PROP_FRAME_COUNT)))
    cap.release()
    center = (slot + 0.5) * total / slots
    start = max(0, min(total - n, round(center - n / 2)))
    return np.linspace(start, min(total - 1, start + n - 1), n).round().astype(int)


def _decode_stage1_clip(path: Path, size: int, frame_ids):
    cap = cv2.VideoCapture(str(path))
    out = []
    wanted = [int(x) for x in frame_ids]
    cap.set(cv2.CAP_PROP_POS_FRAMES, wanted[0])
    pos = wanted[0]
    for idx in wanted:
        ok = False
        bgr = None
        while pos <= idx:
            ok, bgr = cap.read()
            pos += 1
            if not ok:
                break
        if not ok or bgr is None:
            continue
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
        h, w = rgb.shape[:2]
        scale = size / min(h, w)
        nh, nw = max(size, round(h * scale)), max(size, round(w * scale))
        rgb = cv2.resize(rgb, (nw, nh), interpolation=cv2.INTER_AREA)
        y, x = (nh - size) // 2, (nw - size) // 2
        out.append(rgb[y : y + size, x : x + size])
    cap.release()
    if not out:
        raise ValueError(f"cannot decode video: {path.name}")
    while len(out) < len(wanted):
        out.append(out[-1])
    x = torch.from_numpy(np.stack(out)).permute(3, 0, 1, 2).float() / 255.0
    return (x - S1_MEAN) / S1_STD


class Stage1Clips(Dataset):
    def __init__(self, videos, slots, size, frames):
        self.videos = videos
        self.slots = slots
        self.size = size
        self.frames = frames

    def __len__(self):
        return len(self.videos) * self.slots

    def __getitem__(self, index):
        video_index, slot = index // self.slots, index % self.slots
        path = self.videos[video_index]
        try:
            x = _decode_stage1_clip(path, self.size, _clip_ids(path, self.frames, slot, self.slots))
            valid = 1
        except Exception:
            x = torch.zeros(3, self.frames, self.size, self.size)
            valid = 0
        return x, video_index, valid


def predict_stage1(data_dir, model_dir):
    device = _device()
    checkpoint = torch.load(Path(model_dir) / "best.pt", map_location="cpu", weights_only=False)
    size, frames = int(checkpoint["size"]), int(checkpoint["frames"])
    model = Stage1MViT()
    model.net.load_state_dict(checkpoint["model"])
    model.to(device).eval()

    videos = _video_paths(Path(data_dir) / "videos")
    slots = 3
    dataset = Stage1Clips(videos, slots, size, frames)
    loader = DataLoader(dataset, batch_size=4, num_workers=4, pin_memory=True)
    scores = [[] for _ in videos]
    with torch.inference_mode():
        for clips, video_indices, valid in loader:
            with torch.autocast(device_type="cuda", dtype=torch.float16):
                prob = torch.softmax(model(clips.to(device, non_blocking=True)), 1)[:, 1]
            for idx, value, ok in zip(video_indices.tolist(), prob.float().cpu().tolist(), valid.tolist()):
                if ok:
                    scores[idx].append(float(value))

    rows = []
    for path, values in zip(videos, scores):
        probability = float(np.mean(values)) if values else 1.0
        rows.append({"ID": path.stem, "answer": "RERECORDED" if probability >= 0.5 else "ORIGINAL"})
    del model
    torch.cuda.empty_cache()
    return pd.DataFrame(rows, columns=["ID", "answer"])


# ---- src/inference/stage2.py ----
import re
from pathlib import Path

import pandas as pd
import torch
from PIL import Image
from torch import nn
from torch.utils.data import DataLoader, Dataset
from torchvision.models import ResNet18_Weights, resnet18



def _device() -> torch.device:
    if not torch.cuda.is_available():
        raise RuntimeError("DACON inference requires a CUDA GPU.")
    return torch.device("cuda")


class Stage2Frames(Dataset):
    def __init__(self, paths, transform):
        self.paths = paths
        self.transform = transform

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, index):
        with Image.open(self.paths[index]) as image:
            return self.transform(image.convert("RGB"))


def _frame_number(path: Path):
    match = re.search(r"(\d+)$", path.stem)
    return int(match.group(1)) if match else 0


def predict_stage2(data_dir, model_dir):
    device = _device()
    model_dir = Path(model_dir)
    transform = ResNet18_Weights.IMAGENET1K_V1.transforms()
    backbone = resnet18(weights=None)
    backbone.load_state_dict(torch.load(model_dir / "resnet18-f37072fd.pth", map_location="cpu", weights_only=True))
    backbone.fc = nn.Identity()
    backbone.to(device).eval()
    temporal = Stage2Temporal()
    temporal.load_state_dict(torch.load(model_dir / "best.pt", map_location="cpu", weights_only=False)["model"])
    temporal.to(device).eval()

    image_root = Path(data_dir) / "images"
    folders = sorted(p for p in image_root.iterdir() if p.is_dir())
    rows = []
    with torch.inference_mode():
        for folder in folders:
            paths = sorted(
                (p for p in folder.iterdir() if p.suffix.lower() in {".jpg", ".jpeg", ".png"}),
                key=_frame_number,
            )
            if not paths:
                continue
            loader = DataLoader(Stage2Frames(paths, transform), batch_size=256, num_workers=6, pin_memory=True)
            features = []
            for images in loader:
                with torch.autocast(device_type="cuda", dtype=torch.float16):
                    features.append(backbone(images.to(device, non_blocking=True)).float().cpu())
            sequence = torch.cat(features)[None].to(device)
            collision_idx, entry_idx, scene = temporal(sequence)
            frame_numbers = [_frame_number(path) for path in paths]
            rows.append(
                {
                    "ID": folder.name,
                    "collision_frame": frame_numbers[int(collision_idx)],
                    "entry_frame": frame_numbers[int(entry_idx)],
                    "evasion_space": int(scene[:, :2].argmax(1)),
                    "entry_side": "RIGHT" if int(scene[:, 2:].argmax(1)) else "LEFT",
                }
            )
    del backbone, temporal
    torch.cuda.empty_cache()
    return pd.DataFrame(
        rows, columns=["ID", "collision_frame", "entry_frame", "evasion_space", "entry_side"]
    )


# ---- src/inference/stage3.py ----
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import torch
from PIL import Image



ACCEL = ["ACCELERATING", "DECELERATING", "CONSTANT", "STOPPED"]
STEER = ["LEFT", "STRAIGHT", "RIGHT"]


def _device() -> torch.device:
    if not torch.cuda.is_available():
        raise RuntimeError("DACON inference requires a CUDA GPU.")
    return torch.device("cuda")


def _stage3_frames(path: Path):
    capture = cv2.VideoCapture(str(path))
    frames = []
    while True:
        ok, bgr = capture.read()
        if not ok:
            break
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(rgb)
        width, height = image.size
        scale = 256 / min(width, height)
        image = image.resize((round(width * scale), round(height * scale)))
        width, height = image.size
        x, y = (width - 224) // 2, (height - 224) // 2
        image = image.crop((x, y, x + 224, y + 224))
        frames.append(torch.from_numpy(np.asarray(image).copy()).permute(2, 0, 1).to(torch.uint8))
    capture.release()
    if not frames:
        raise ValueError(f"cannot decode video: {path.name}")
    return torch.stack(frames)


def predict_stage3(data_dir, model_dir):
    device = _device()
    checkpoint = torch.load(Path(model_dir) / "best.pt", map_location="cpu", weights_only=False)
    model = Stage3MViT()
    model.load_state_dict(checkpoint["model"])
    model.to(device).eval()
    videos = _video_paths(Path(data_dir) / "videos")
    rows = []
    with torch.inference_mode():
        for path in videos:
            frames = _stage3_frames(path)
            count = len(frames)
            centers = np.arange(count)
            accel_predictions, steer_predictions = [], []
            for start in range(0, count, 8):
                center = centers[start : start + 8]
                indices = np.clip(center[:, None] - 8 + np.arange(16)[None, :], 0, count - 1)
                clips = frames[torch.from_numpy(indices)].permute(0, 2, 1, 3, 4).float() / 255.0
                clips = (clips - S3_MEAN[None, :, None, :, :]) / S3_STD[None, :, None, :, :]
                with torch.autocast(device_type="cuda", dtype=torch.float16):
                    accel_logits, steer_logits = model(clips.to(device, non_blocking=True))
                accel_predictions.extend(accel_logits.argmax(1).cpu().tolist())
                steer_predictions.extend(steer_logits.argmax(1).cpu().tolist())
            for sample_index, (accel, steer) in enumerate(zip(accel_predictions, steer_predictions)):
                rows.append(
                    {
                        "ID": path.stem,
                        "sample_index": sample_index,
                        "accel_label": ACCEL[accel],
                        "steer_label": STEER[steer],
                    }
                )
    del model
    torch.cuda.empty_cache()
    return pd.DataFrame(rows, columns=["ID", "sample_index", "accel_label", "steer_label"])
