import os
import platform
from pathlib import Path

import torch

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ROOT = PROJECT_ROOT

SYSTEM = platform.system()

_data_root = os.getenv("DACON_DATA_ROOT")
if _data_root:
    DATA_ROOT = Path(_data_root).expanduser()
elif SYSTEM == "Windows":
    DATA_ROOT = PROJECT_ROOT / "data"
elif SYSTEM == "Linux":
    DATA_ROOT = Path("/data")
else:
    raise RuntimeError(f"Unsupported operating system: {SYSTEM}")

DATA = DATA_ROOT
MODEL = PROJECT_ROOT / "model"

STAGE1_MODEL = MODEL / "stage1"
STAGE2_MODEL = MODEL / "stage2"
STAGE2_CHECKPOINT = STAGE2_MODEL / "best.pt"
STAGE2_VIDEOMAE_MODEL = STAGE2_MODEL
STAGE2_VIDEOMAE_CHECKPOINT = STAGE2_CHECKPOINT
STAGE3_MODEL = MODEL / "stage3"
TARTANVO_CHECKPOINT = STAGE3_MODEL / "tartanvo_1914.pkl"
# ============================================================
# Data directories
# ============================================================

RAW_DATA = DATA / "raw"
PROCESSED_DATA = DATA / "processed"

TOOLS_DATA = PROJECT_ROOT / "src" / "tools" / "data"


# Stage 1
STAGE1_RAW = RAW_DATA / "stage1"
STAGE1_PROCESSED = PROCESSED_DATA / "stage1"

# Stage 2
STAGE2_RAW = RAW_DATA / "stage2"
STAGE2_PROCESSED = PROCESSED_DATA / "stage2"

# Stage 3
STAGE3_RAW = RAW_DATA
STAGE3_PROCESSED = PROCESSED_DATA / "stage3"
COMMA2K19_STAGE3_RAW = RAW_DATA / "comma2k19"
COMMA2K19_STAGE3_PROCESSED = STAGE3_PROCESSED
COMMA2K19_STAGE3_MANIFEST = COMMA2K19_STAGE3_PROCESSED / "manifest"
COMMA2K19_STAGE3_TRAIN_MANIFEST = COMMA2K19_STAGE3_MANIFEST / "train.csv"
COMMA2K19_STAGE3_VAL_MANIFEST = COMMA2K19_STAGE3_MANIFEST / "val.csv"
COMMA2K19_STAGE3_FRAME_CACHE = STAGE3_PROCESSED / "comma2k19_frames"
KITTI_STAGE3_RAW = RAW_DATA / "stage3" / "kitti"
KITTI_STAGE3_PROCESSED = STAGE3_PROCESSED / "kitti"
KITTI_STAGE3_MANIFEST = KITTI_STAGE3_PROCESSED / "manifest"
KITTI_STAGE3_TRAIN_MANIFEST = KITTI_STAGE3_MANIFEST / "train.csv"
KITTI_STAGE3_VAL_MANIFEST = KITTI_STAGE3_MANIFEST / "val.csv"
KITTI_STAGE3_SPLIT_CSV = KITTI_STAGE3_MANIFEST / "sequence_split.csv"
KITTI_STAGE3_SPLIT_JSON = KITTI_STAGE3_MANIFEST / "sequence_split.json"
STAGE3_USE_NUSCENES = False
STAGE3_NUSCENES_ROOT = RAW_DATA / "stage3" / "nuscenes"
STAGE3_NUSCENES_VERSION = "v1.0-mini"
STAGE3_NUSCENES_PROCESSED = STAGE3_PROCESSED / "nuscenes"
STAGE3_NUSCENES_MANIFEST = STAGE3_NUSCENES_PROCESSED / "nuscenes_mini_manifest.csv"
STAGE3_NUSCENES_TRAIN_MANIFEST = STAGE3_NUSCENES_PROCESSED / "train.csv"
STAGE3_NUSCENES_VAL_MANIFEST = STAGE3_NUSCENES_PROCESSED / "val.csv"

# Backward-compatible aliases for stage raw data roots.
STAGE1_DATA = STAGE1_RAW
STAGE2_DATA = STAGE2_RAW
STAGE3_DATA = STAGE3_RAW


# ============================================================
# Stage 1 datasets
# ============================================================

AIHUB_STAGE1_RAW = STAGE1_RAW / "aihub597"
AIHUB_STAGE1_PROCESSED = STAGE1_PROCESSED / "aihub597"
AIHUB_STAGE1_MANIFEST = AIHUB_STAGE1_PROCESSED / "manifest"

DLC_STAGE1_RAW = STAGE1_RAW / "dlc2021"
DLC_STAGE1_PROCESSED = STAGE1_PROCESSED / "dlc2021"
DLC_STAGE1_MANIFEST = DLC_STAGE1_PROCESSED / "manifest"

CCD_STAGE2_RAW = STAGE2_RAW / "CCD-1500"
CCD_STAGE2_PROCESSED = STAGE2_PROCESSED / "CCD-1500"
CCD_STAGE2_MANIFEST = CCD_STAGE2_PROCESSED / "manifest"
STAGE2_MANIFEST = STAGE2_PROCESSED / "manifest"
STAGE2_ALL_MANIFEST = STAGE2_MANIFEST / "all.csv"
STAGE2_TRAIN_MANIFEST = STAGE2_MANIFEST / "train.csv"
STAGE2_VAL_MANIFEST = STAGE2_MANIFEST / "val.csv"
STAGE2_BACKBONE = "small"

CCD_STAGE2_TOOL_DATA = TOOLS_DATA / "stage2" / "CCD-1500"
CCD_STAGE2_BOTSORT_TRACKS = CCD_STAGE2_TOOL_DATA / "tracks" / "botsort"
CCD_STAGE2_COLLISION_CANDIDATES = CCD_STAGE2_TOOL_DATA / "collision_candidates" / "collision_candidates.csv"

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
EPOCHS = 3
TRAIN_SOURCE_LIMIT = 4000

SIZE = 224
BATCH_SIZE = 2
STAGE3_DATASET = "comma_only"
STAGE3_DATASET_MODE = STAGE3_DATASET
STAGE3_EPOCHS = 20
STAGE3_ARCH = "tartanvo_gru"
STAGE3_TARTANVO_FEATURE = "latent"
STAGE3_TARTANVO_MODE = "cached"
STAGE3_TARTANVO_UNFREEZE = "none"
STAGE3_TARTANVO_LR = 1e-5
STAGE3_HEAD_LR = 1e-4
STAGE3_TARTANVO_USE_FEATURE_CACHE = True
STAGE3_TARTANVO_FEATURE_CACHE = STAGE3_PROCESSED / "tartanvo_features"
STAGE3_TARTANVO_CACHE_PAIR_BATCH_SIZE = 16
STAGE3_SEGMENT_FEATURE_LRU_SIZE = 8
STAGE3_TARTANVO_FEATURE_NORM = "layernorm"
STAGE3_TARTANVO_POSE_NORM = "none"
STAGE3_TARTANVO_HEIGHT = 448
STAGE3_TARTANVO_WIDTH = 640
STAGE3_NUM_FRAMES = 16
STAGE3_OUTPUT_HZ = 10.0
STAGE3_ACCEL_LABEL_MODE = "current"
STAGE3_ACCEL_THRESHOLD = 0.35
STAGE3_DECEL_THRESHOLD = 0.5
STAGE3_STOP_SPEED_THRESHOLD = 0.5
STAGE3_ACCEL_WINDOW_SECONDS = 0.8
STAGE3_STEER_THRESHOLD_DEG = 5.0
STAGE3_STEER_THRESHOLD = STAGE3_STEER_THRESHOLD_DEG
STAGE3_STEER_POSITIVE_IS = "LEFT"
STAGE3_LOSS_WEIGHTS = {"accel": 1.0, "steer": 1.0}
STAGE3_CLASS_WEIGHTS = {"accel": None,
    "steer": [1.5, 1.0, 1.5],}
# LEFT      150
# STRAIGHT  200
# RIGHT     150
STAGE3_TRAIN_TEMPORAL_STRIDE = 50
STAGE3_VAL_TEMPORAL_STRIDE = 50
STAGE3_NUM_WORKERS = 1
COMMA2K19_STAGE3_FRAME_CACHE = STAGE3_PROCESSED / "comma2k19_frames"
STAGE3_FRAME_CACHE_JPEG_QUALITY = 92
STAGE3_TRAIN_SAMPLE_LIMIT = 3000
STAGE3_VAL_SAMPLE_LIMIT = 500
STAGE3_COMMA_TRAIN_SAMPLE_LIMIT = 5000
STAGE3_COMMA_VAL_SAMPLE_LIMIT = 1000
STAGE3_SOURCE_BALANCED_SAMPLING = True
STAGE3_KITTI_TRAIN_SAMPLE_LIMIT = 5000
STAGE3_KITTI_VAL_SAMPLE_LIMIT = 1000
STAGE3_NUSCENES_SAMPLE_LIMIT = 1000
STAGE3_NUSCENES_YAW_SIGN = 1
KITTI_SPEED_SMOOTH_WINDOW = 5
KITTI_INVERT_YAW = False
KITTI_STOP_SPEED_THRESHOLD = 0.5
KITTI_ACCEL_THRESHOLD = 0.5
KITTI_YAW_RATE_THRESHOLD = 0.12
STAGE3_NUSCENES_YAW_RATE_THRESHOLD = KITTI_YAW_RATE_THRESHOLD
KITTI_SPEED_SMOOTH_METHOD = "moving_average"
KITTI_MAX_SPEED = 35.0
KITTI_MAX_ABS_ACCELERATION = 15.0

S1_MEAN = torch.tensor([0.45, 0.45, 0.45])[:, None, None, None]
S1_STD = torch.tensor([0.225, 0.225, 0.225])[:, None, None, None]
S3_MEAN = torch.tensor([0.45, 0.45, 0.45])[:, None, None]
S3_STD = torch.tensor([0.225, 0.225, 0.225])[:, None, None]

SEED = 42




